<a href="https://colab.research.google.com/github/WashMarvin/Algoritmo_kmeans/blob/master/Desafio_mod_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px # Criar gráficos dinâmicos
import plotly.graph_objects as go # Criação e concatenação de gráficos
#from sklearn.preprocessing import StandardScaler # Para realizar a padronização dos dados
from sklearn.cluster import KMeans

In [2]:
# Buscando os dados dos clientes
url_clientes = 'https://raw.githubusercontent.com/WashMarvin/Algoritmo_kmeans/master/dados_clientes.csv'

In [3]:
dados_clientes = pd.read_csv(url_clientes, sep=';', encoding='latin-1')

In [4]:
dados_clientes.head()

   id_cliente   peso  colesterol     genero  id_estado
0           1  102.0         111  Masculino         23
1           2  115.0         135  Masculino          7
2           3  115.0         136  Masculino          4
3           4  140.0         167   Feminino         24
4           5  130.0         158  Masculino         26

In [5]:
# Buscando os dados dos estados
url_estados = 'https://raw.githubusercontent.com/WashMarvin/Algoritmo_kmeans/master/estados_brasileiros.csv'

In [6]:
dados_estados = pd.read_csv(url_estados, sep=';', encoding='latin-1')

In [7]:
dados_estados.head()

   id_estado    estado sigla_estado    pais
0          1      Acre           ac  Brasil
1          2   Alagoas           al  Brasil
2          3     Amapá           ap  Brasil
3          4  Amazonas           am  Brasil
4          5     Bahia           ba  Brasil

In [8]:
# Buscando os dados das idades
url_idade = 'https://raw.githubusercontent.com/WashMarvin/Algoritmo_kmeans/master/idade_clientes.csv'

In [9]:
idade_clientes = pd.read_csv(url_idade, sep=';', encoding='latin-1')

In [10]:
idade_clientes.head()

   id_cliente  idade
0           1     17
1           2     28
2           3     62
3           4     55
4           5     44

### Analisando os dados estatísticos das bases de dados

In [11]:
dados_clientes.describe()

       id_cliente        peso  colesterol   id_estado
count   547.00000  542.000000  547.000000  547.000000
mean    274.00000  143.440959  170.433272   13.833638
std     158.04957   30.836868   39.147189    7.593117
min       1.00000   95.000000  102.000000    1.000000
25%     137.50000  116.000000  136.000000    7.000000
50%     274.00000  140.000000  169.000000   13.000000
75%     410.50000  171.000000  208.000000   20.000000
max     547.00000  203.000000  235.000000   27.000000

In [12]:
dados_estados.describe()

       id_estado
count  27.000000
mean   14.000000
std     7.937254
min     1.000000
25%     7.500000
50%    14.000000
75%    20.500000
max    27.000000

In [13]:
idade_clientes.describe()

       id_cliente       idade
count   547.00000  547.000000
mean    274.00000   42.791590
std     158.04957   15.160209
min       1.00000   16.000000
25%     137.50000   30.000000
50%     274.00000   42.000000
75%     410.50000   55.000000
max     547.00000   70.000000

### Identificando os dados ausentes

In [14]:
dados_clientes.isna().sum()

id_cliente    0
peso          5
colesterol    0
genero        0
id_estado     0
dtype: int64

In [15]:
dados_estados.isna().sum()

id_estado       0
estado          0
sigla_estado    0
pais            2
dtype: int64

In [16]:
idade_clientes.isna().sum()

id_cliente    0
idade         0
dtype: int64

### Verificando os registros com valores nulos

In [17]:
dados_clientes.loc[dados_clientes['peso'].isnull()]

     id_cliente  peso  colesterol     genero  id_estado
63           64   NaN         211  Masculino         12
101         102   NaN         230   Feminino         24
146         147   NaN         171  Masculino         23
195         196   NaN         143   Feminino         15
215         216   NaN         180  Masculino         13

In [18]:
dados_estados.loc[dados_estados['pais'].isnull()]

    id_estado          estado sigla_estado pais
17         18           Piauí           pi  NaN
23         24  Santa Catarina           sc  NaN

### Eliminando os registros ausentes

In [19]:
dados_clientes.dropna(subset=['peso'], inplace=True)

In [20]:
dados_clientes.isna().sum()

id_cliente    0
peso          0
colesterol    0
genero        0
id_estado     0
dtype: int64

In [21]:
dados_estados.dropna(subset=['pais'], inplace=True)

In [22]:
dados_estados.isna().sum()

id_estado       0
estado          0
sigla_estado    0
pais            0
dtype: int64

### Refatorando valores estatísticos dos dados

In [23]:
dados_clientes.describe()

       id_cliente        peso  colesterol   id_estado
count  542.000000  542.000000  542.000000  542.000000
mean   275.190037  143.440959  170.280443   13.800738
std    158.194932   30.836868   39.185218    7.604659
min      1.000000   95.000000  102.000000    1.000000
25%    138.250000  116.000000  136.000000    7.000000
50%    276.500000  140.000000  169.000000   13.000000
75%    411.750000  171.000000  207.750000   20.000000
max    547.000000  203.000000  235.000000   27.000000

In [24]:
dados_estados.describe()

       id_estado
count  25.000000
mean   13.440000
std     7.942921
min     1.000000
25%     7.000000
50%    13.000000
75%    20.000000
max    27.000000

In [25]:
idade_clientes.describe()

       id_cliente       idade
count   547.00000  547.000000
mean    274.00000   42.791590
std     158.04957   15.160209
min       1.00000   16.000000
25%     137.50000   30.000000
50%     274.00000   42.000000
75%     410.50000   55.000000
max     547.00000   70.000000

### Junção das tabelas

In [26]:
dados_clientes[:10]

   id_cliente   peso  colesterol     genero  id_estado
0           1  102.0         111  Masculino         23
1           2  115.0         135  Masculino          7
2           3  115.0         136  Masculino          4
3           4  140.0         167   Feminino         24
4           5  130.0         158  Masculino         26
5           6  198.0         227  Masculino          8
6           7  114.0         131  Masculino         26
7           8  145.0         176   Feminino         25
8           9  191.0         223   Feminino         16
9          10  186.0         221  Masculino          6

In [27]:
dados_estados[:10]

   id_estado            estado sigla_estado    pais
0          1              Acre           ac  Brasil
1          2           Alagoas           al  Brasil
2          3             Amapá           ap  Brasil
3          4          Amazonas           am  Brasil
4          5             Bahia           ba  Brasil
5          6             Ceará           ce  Brasil
6          7  Distrito Federal           df  Brasil
7          8    Espírito Santo           es  Brasil
8          9             Goiás           go  Brasil
9         10          Maranhão           ma  Brasil

In [28]:
clientes_estados = pd.merge(dados_clientes, dados_estados, on='id_estado')
clientes_estados.sort_values('id_cliente') # Ordena pelo valor do id do cliente

,id_cliente,peso,colesterol,genero,id_estado,estado,sigla_estado,pais
0,1,102.0,111,Masculino,23,Roraima,rr,Brasil
17,2,115.0,135,Masculino,7,Distrito Federal,df,Brasil
39,3,115.0,136,Masculino,4,Amazonas,am,Brasil
64,5,130.0,158,Masculino,26,Sergipe,se,Brasil
83,6,198.0,227,Masculino,8,Espírito Santo,es,Brasil
...,...,...,...,...,...,...,...,...
418,543,172.0,207,Masculino,22,Rondônia,ro,Brasil
430,544,129.0,157,Masculino,1,Acre,ac,Brasil
155,545,107.0,115,Masculino,6,Ceará,ce,Brasil
372,546,117.0,147,Masculino,20,Rio Grande do Norte,rn,Brasil
100,547,148.0,176,Masculino,8,Espírito Santo,es,Brasil

In [29]:
# Junção das bases cliente e estado com as bases das idades
base_completa = pd.merge(idade_clientes, clientes_estados, on='id_cliente')
base_completa.sort_values('id_cliente')

,id_cliente,idade,peso,colesterol,genero,id_estado,estado,sigla_estado,pais
0,1,17,102.0,111,Masculino,23,Roraima,rr,Brasil
1,2,28,115.0,135,Masculino,7,Distrito Federal,df,Brasil
2,3,62,115.0,136,Masculino,4,Amazonas,am,Brasil
3,5,44,130.0,158,Masculino,26,Sergipe,se,Brasil
4,6,17,198.0,227,Masculino,8,Espírito Santo,es,Brasil
...,...,...,...,...,...,...,...,...,...
493,543,20,172.0,207,Masculino,22,Rondônia,ro,Brasil
494,544,66,129.0,157,Masculino,1,Acre,ac,Brasil
495,545,36,107.0,115,Masculino,6,Ceará,ce,Brasil
496,546,57,117.0,147,Masculino,20,Rio Grande do Norte,rn,Brasil
497,547,61,148.0,176,Masculino,8,Espírito Santo,es,Brasil

In [30]:
# Organizando os nomes das colunas para uma melhor legibilidade
base_completa.rename(columns={'id_cliente': 'cod_cliente', 'id_estado': 'cod_estado', 'sigla_estado': 'sigla'}, inplace=True)
base_completa

,cod_cliente,idade,peso,colesterol,genero,cod_estado,estado,sigla,pais
0,1,17,102.0,111,Masculino,23,Roraima,rr,Brasil
1,2,28,115.0,135,Masculino,7,Distrito Federal,df,Brasil
2,3,62,115.0,136,Masculino,4,Amazonas,am,Brasil
3,5,44,130.0,158,Masculino,26,Sergipe,se,Brasil
4,6,17,198.0,227,Masculino,8,Espírito Santo,es,Brasil
...,...,...,...,...,...,...,...,...,...
493,543,20,172.0,207,Masculino,22,Rondônia,ro,Brasil
494,544,66,129.0,157,Masculino,1,Acre,ac,Brasil
495,545,36,107.0,115,Masculino,6,Ceará,ce,Brasil
496,546,57,117.0,147,Masculino,20,Rio Grande do Norte,rn,Brasil
497,547,61,148.0,176,Masculino,8,Espírito Santo,es,Brasil

In [31]:
base_completa.sigla.str.upper()

0      RR
1      DF
2      AM
3      SE
4      ES
       ..
493    RO
494    AC
495    CE
496    RN
497    ES
Name: sigla, Length: 498, dtype: object

In [32]:
base_completa['sigla'] = base_completa.sigla.str.upper()
base_completa

,cod_cliente,idade,peso,colesterol,genero,cod_estado,estado,sigla,pais
0,1,17,102.0,111,Masculino,23,Roraima,RR,Brasil
1,2,28,115.0,135,Masculino,7,Distrito Federal,DF,Brasil
2,3,62,115.0,136,Masculino,4,Amazonas,AM,Brasil
3,5,44,130.0,158,Masculino,26,Sergipe,SE,Brasil
4,6,17,198.0,227,Masculino,8,Espírito Santo,ES,Brasil
...,...,...,...,...,...,...,...,...,...
493,543,20,172.0,207,Masculino,22,Rondônia,RO,Brasil
494,544,66,129.0,157,Masculino,1,Acre,AC,Brasil
495,545,36,107.0,115,Masculino,6,Ceará,CE,Brasil
496,546,57,117.0,147,Masculino,20,Rio Grande do Norte,RN,Brasil
497,547,61,148.0,176,Masculino,8,Espírito Santo,ES,Brasil

In [33]:
# Alterando as disposições das colunas para uma melhor visuaização da base de dados
base_completa[['cod_cliente', 'cod_estado', 'genero', 'idade', 'peso', 'colesterol', 'estado', 'pais']]

,cod_cliente,cod_estado,genero,idade,peso,colesterol,estado,pais
0,1,23,Masculino,17,102.0,111,Roraima,Brasil
1,2,7,Masculino,28,115.0,135,Distrito Federal,Brasil
2,3,4,Masculino,62,115.0,136,Amazonas,Brasil
3,5,26,Masculino,44,130.0,158,Sergipe,Brasil
4,6,8,Masculino,17,198.0,227,Espírito Santo,Brasil
...,...,...,...,...,...,...,...,...
493,543,22,Masculino,20,172.0,207,Rondônia,Brasil
494,544,1,Masculino,66,129.0,157,Acre,Brasil
495,545,6,Masculino,36,107.0,115,Ceará,Brasil
496,546,20,Masculino,57,117.0,147,Rio Grande do Norte,Brasil
497,547,8,Masculino,61,148.0,176,Espírito Santo,Brasil

### Análise de dados - Seleção do algoritmo de Machine Learning
#### Agrupamento de pessoas baseados no peso e colesterol utilizando o método cotovelo

In [34]:
from re import X
def calcular_wcss(clientes):
  wcss = []
  for i in range(1, 11):
    kmeans = KMeans(n_clusters = i, random_state = 0)
    kmeans.fit(X = clientes)
    wcss.append(kmeans.inertia_)
  return wcss

In [35]:
clientes = base_completa[['peso', 'colesterol']]
clientes.head()

    peso  colesterol
0  102.0         111
1  115.0         135
2  115.0         136
3  130.0         158
4  198.0         227

In [36]:
type(clientes)

pandas.core.frame.DataFrame

In [37]:
wcss_clientes = calcular_wcss(clientes)

In [38]:
type(wcss_clientes)

list

In [39]:
for i in range(len(wcss_clientes)):
  print(f'O cluster {i} possui o valor de :', wcss_clientes[i])

O cluster 0 possui o valor de : 1248240.6686746986
O cluster 1 possui o valor de : 298932.7377352369
O cluster 2 possui o valor de : 127842.60787249672
O cluster 3 possui o valor de : 73809.93553059456
O cluster 4 possui o valor de : 49068.8738718445
O cluster 5 possui o valor de : 34064.50002100837
O cluster 6 possui o valor de : 25079.92393550797
O cluster 7 possui o valor de : 20378.05126656164
O cluster 8 possui o valor de : 16003.657266380145
O cluster 9 possui o valor de : 13385.38391038145

In [40]:
# Visualizando o gráfico
grafico_cliente = px.line( x = range(1, 11), y = wcss_clientes)
grafico_cliente.show()

In [41]:
kmeans_clientes = KMeans(n_clusters = 4, random_state = 0)
label_cluster_clientes = kmeans_clientes.fit_predict(clientes)

In [42]:
label_cluster_clientes

array([2, 2, 2, 1, 0, 2, 3, 0, 0, 2, 0, 2, 3, 1, 0, 2, 0, 3, 1, 3, 2, 0,
       1, 2, 0, 2, 0, 0, 3, 0, 1, 3, 0, 2, 0, 2, 1, 3, 0, 3, 1, 0, 1, 0,
       1, 1, 2, 2, 3, 0, 3, 2, 3, 3, 0, 1, 3, 2, 3, 2, 1, 3, 3, 0, 1, 1,
       1, 1, 3, 0, 2, 1, 0, 2, 1, 1, 2, 0, 1, 2, 1, 3, 1, 1, 2, 3, 0, 2,
       2, 2, 1, 1, 3, 2, 2, 3, 1, 0, 2, 3, 2, 0, 1, 0, 1, 2, 0, 2, 1, 3,
       1, 0, 2, 3, 0, 0, 2, 0, 2, 1, 0, 2, 0, 3, 1, 3, 2, 0, 3, 2, 0, 2,
       0, 0, 3, 3, 2, 0, 2, 0, 2, 1, 0, 0, 1, 0, 0, 0, 1, 1, 3, 0, 3, 2,
       0, 3, 0, 1, 3, 2, 3, 2, 0, 3, 3, 0, 1, 1, 1, 1, 3, 0, 2, 1, 0, 2,
       1, 2, 0, 1, 2, 1, 3, 3, 1, 2, 3, 0, 2, 2, 2, 1, 1, 3, 2, 2, 0, 2,
       1, 0, 0, 1, 2, 0, 0, 1, 2, 0, 2, 1, 1, 1, 0, 2, 3, 0, 2, 0, 2, 3,
       1, 0, 2, 0, 3, 1, 3, 2, 0, 2, 0, 2, 0, 0, 3, 0, 3, 3, 0, 2, 0, 2,
       1, 0, 0, 3, 1, 0, 1, 0, 1, 1, 2, 1, 0, 0, 3, 2, 3, 3, 0, 3, 2, 3,
       2, 0, 3, 3, 2, 3, 0, 1, 1, 1, 3, 0, 2, 1, 0, 2, 1, 2, 0, 1, 2, 1,
       3, 3, 1, 2, 3, 0, 2, 2, 2, 1, 1, 3, 2, 2, 3, 0, 2, 1, 0, 0, 2, 3,
       2, 0, 1, 0, 1, 2, 0, 2, 1, 1, 3, 1, 0, 2, 3, 0, 0, 2, 0, 2, 1, 0,
       0, 3, 1, 3, 2, 0, 3, 2, 0, 2, 0, 0, 0, 1, 3, 2, 0, 2, 0, 2, 0, 0,
       3, 1, 0, 0, 0, 1, 1, 1, 3, 0, 3, 2, 3, 0, 1, 3, 2, 3, 0, 3, 3, 2,
       3, 0, 1, 1, 1, 1, 3, 0, 2, 1, 0, 2, 1, 2, 0, 2, 1, 3, 1, 1, 2, 3,
       2, 2, 2, 1, 1, 3, 2, 2, 3, 0, 1, 0, 0, 1, 3, 2, 0, 1, 0, 1, 2, 0,
       2, 1, 1, 3, 1, 1, 3, 0, 0, 2, 0, 2, 3, 1, 0, 2, 0, 3, 1, 3, 0, 3,
       2, 0, 2, 0, 0, 3, 0, 3, 3, 2, 2, 0, 2, 1, 0, 3, 1, 0, 0, 1, 0, 1,
       1, 2, 3, 0, 3, 2, 3, 3, 0, 1, 3, 2, 2, 3, 3, 2, 3, 0, 3, 1, 1, 1,
       3, 0, 2, 1, 0, 2, 1, 1, 2, 0, 1, 2, 1, 3], dtype=int32)

In [43]:
centroides_clientes = kmeans_clientes.cluster_centers_
centroides_clientes

array([[184.32394366, 218.98591549],
       [127.57024793, 154.20661157],
       [106.90697674, 119.57364341],
       [152.32075472, 186.03773585]])

In [55]:
base_completa['cluster'] = label_cluster_clientes
base_completa.head()

,cod_cliente,idade,peso,colesterol,genero,cod_estado,estado,sigla,pais,cluster
0,1,17,102.0,111,Masculino,23,Roraima,RR,Brasil,2
1,2,28,115.0,135,Masculino,7,Distrito Federal,DF,Brasil,2
2,3,62,115.0,136,Masculino,4,Amazonas,AM,Brasil,2
3,5,44,130.0,158,Masculino,26,Sergipe,SE,Brasil,1
4,6,17,198.0,227,Masculino,8,Espírito Santo,ES,Brasil,0

In [44]:
dados_clientes = clientes.iloc[:,[0,1]].values
dados_clientes[:10]

array([[102., 111.],
       [115., 135.],
       [115., 136.],
       [130., 158.],
       [198., 227.],
       [114., 131.],
       [145., 176.],
       [191., 223.],
       [186., 221.],
       [104., 116.]])

### Gráfico de agrupamentos dos valores de peso e colesterol

In [61]:
grafico_clientes = px.scatter(x = base_completa['peso'], y = base_completa['colesterol'], color = base_completa['cluster'])
grafico_centroides = px.scatter(x = centroides_clientes[:,0], y = centroides_clientes[:,1], size = [7,7,7,7])
grafico_final = go.Figure(data = grafico_clientes.data + grafico_centroides.data)
grafico_final.show()

In [67]:
grafico = px.scatter( x = base_completa['peso'], y = base_completa['colesterol'], color = base_completa['cluster'])
fig = go.Figure(grafico)
fig.update_layout(title = 'Análise', xaxis_title = 'colesterol', yaxis_title = 'peso',)
fig.show()

In [68]:
def plotar_grafico(x, y, xlabel, ylabel):
  grafico = px.scatter(x = x, y = y, color = base_completa['cluster'])
  fig = go.Figure(grafico)
  fig.update_layout(title = 'Análise', xaxis_title = xlabel, yaxis_title = ylabel,)
  fig.show()

In [71]:
plotar_grafico(base_completa['colesterol'], base_completa['peso'], 'colesterol', 'peso')

In [72]:
plotar_grafico(base_completa['idade'], base_completa['colesterol'], 'idade', 'colesterol')

In [73]:
cluster_clientes = base_completa

In [74]:
cluster_clientes.loc[cluster_clientes['cluster'] == 3, 'nome_cluster'] = 'Alto Risco'
cluster_clientes.loc[cluster_clientes['cluster'] == 2, 'nome_cluster'] = 'Risco Moderado Alto'
cluster_clientes.loc[cluster_clientes['cluster'] == 1, 'nome_cluster'] = 'Risco Moderado Baixo'
cluster_clientes.loc[cluster_clientes['cluster'] == 0, 'nome_cluster'] = 'Baixo Risco'

In [75]:
cluster_clientes.query('nome_cluster == "Alto Risco" & estado == "Mato Grosso"')

,cod_cliente,idade,peso,colesterol,genero,cod_estado,estado,sigla,pais,cluster,nome_cluster
155,172,61,161.0,201,Feminino,11,Mato Grosso,MT,Brasil,3,Alto Risco
466,514,42,151.0,184,Masculino,11,Mato Grosso,MT,Brasil,3,Alto Risco
476,526,30,152.0,193,Masculino,11,Mato Grosso,MT,Brasil,3,Alto Risco

In [76]:
cluster_clientes.groupby(['nome_cluster', 'genero'])['peso'].describe()

                                count        mean        std    min     25%  \
nome_cluster         genero
Alto Risco           Feminino    59.0  152.135593   7.300112  140.0  145.00
                     Masculino   47.0  152.553191   6.730232  140.0  148.00
Baixo Risco          Feminino    60.0  185.983333   8.032754  168.0  180.00
                     Masculino   82.0  183.109756  10.743940  167.0  173.25
Risco Moderado Alto  Feminino    58.0  108.396552   6.472451   96.0  104.00
                     Masculino   71.0  105.690141   5.953610   95.0  101.50
Risco Moderado Baixo Feminino    63.0  129.317460   7.079788  116.0  125.00
                     Masculino   58.0  125.672414   6.383608  115.0  120.25

                                  50%     75%    max
nome_cluster         genero
Alto Risco           Feminino   154.0  157.00  169.0
                     Masculino  151.0  154.50  168.0
Baixo Risco          Feminino   186.0  192.00  203.0
                     Masculino  182.0  189.75  203.0
Risco Moderado Alto  Feminino   110.0  113.00  118.0
                     Masculino  105.0  110.00  118.0
Risco Moderado Baixo Feminino   129.0  135.00  142.0
                     Masculino  125.5  131.00  140.0

In [77]:
cluster_clientes.to_csv('classificacao_clientes.csv', sep=';', encoding='ISO-8859-1')